### ISSUE TITLE
Add Videos listing page

### ISSUE THREAD

**Issue by NivethaMegalai** [ajitsinghkaler/devto-clone#15]
I would like to work on video listing [page ](https://dev.to/videos) 
Shall I work on this ?

**Comment by ajitsinghkaler** [comment]
Yeah sure. You know the rules right you have to publish detailed info for me to write article on our progress. First you will have to write detailed info on this issue.

If you are ready for writing detaied info let me know your twitter so that we can connect easily. Send me dm at https://twitter.com/ajitsinghkaler

Please star the repo too

**Comment by ajitsinghkaler** [comment]
Let me know if this works for you

**Comment by NivethaMegalai** [comment]
When video menu is clicked it will render video modules,  under which I will create a parent component which will contain card child component. Using component store I will get data to render the child compoent.

**Comment by NivethaMegalai** [comment]
I will follow you on twitter soon and ping you

**Comment by ajitsinghkaler** [comment]
Please star the repo

**Comment by NivethaMegalai** [comment]
Today I have forked the repo and started working on the Video listing page.

**Comment by NivethaMegalai** [comment]
I have created a pull request for Video listing page. Kindly let me know your feed back

**Comment by ajitsinghkaler** [comment]
Fixed with https://github.com/ajitsinghkaler/devto-clone/pull/18
